use_frameworks!

target 'CoreDataHelper_Example' do
  pod 'CoreDataHelper', :path => '../'

  target 'CoreDataHelper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
